apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: orders-api
  namespace: monitoring
  labels:
    app: orders-api
    release: prometheus
spec:
  selector:
    matchLabels:
      app: orders-api
  namespaceSelector:
    matchNames:
    - cloudshop-prod
  endpoints:
  - port: http
    interval: 30s
    path: /metrics
    scheme: http
